# Generated by Django 5.1.1 on 2024-10-01 16:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Instructor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("last_name", models.CharField(max_length=100)),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("REGULAR", "Regular"),
                            ("COS", "Contract of Service"),
                            ("Not Specified", "Not Specified"),
                        ],
                        default="Not Specified",
                        max_length=15,
                    ),
                ),
                ("qualified_course", models.JSONField(default=list)),
                ("availability_days", models.DateField(default=datetime.date.today)),
                ("availability_times", models.TimeField(default=datetime.time(0, 0))),
            ],
            options={
                'db_table': 'instructors',  # Check this is 'instructors'
            },
        ),
    ]
