# Generated by Django 5.1.1 on 2024-10-02 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("instructors", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="instructor",
            table="instructors",
        ),
    ]
